---
collections:

  - name: arista.avd
    version: 5.5.1

  - name: arista.cvp
    version: 3.12.0

  - name: community.general
    version: 11.1.1

roles:  
  - name: avd_topo_gen
    src: https://github.com/kpbush30/avd_topo_gen.git
    scm: git
    version: main